name: Build and deploy
on: [push]
jobs:
  create_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instala node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Instala dependencias
        run: npm install
      - name: Crea un nuevo build
        run: npm run build
      - name: Guarda build
        if: success()
        run: |
          git config --global user.name 'christopherorea'
          git config --global user.email 'c28_09_98@hotmail.com'
          git checkout -b "gh-pages"
          mv build/* .
          git add .
          git commit -am "Nuevo website"
          git push --force --set-upstream origin gh-pages